x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  backend:
    build:
      context: ./backend/demo
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - JAVA_OPTS=-Xms256m -Xmx768m -Xss256k -XX:MaxMetaspaceSize=128m -XX:+UseSerialGC
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.20"
          memory: 1024M
    logging: *default-logging
    networks:
      - kamp-network

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./maria_db/data:/var/lib/mysql
    # Порт закрыт для внешней сети ради безопасности,
    # если нужен доступ извне - раскомментируй строку ниже
    ports:
      - "127.0.0.1:3306:3306"
    command: >
      --performance_schema=0 
      --innodb_buffer_pool_size=128M 
      --max_connections=50 
      --key_buffer_size=16M 
      --query_cache_size=0 
      --query_cache_type=0
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$${MARIADB_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 400M
    logging: *default-logging
    networks:
      - kamp-network

networks: # <-- Исправлен уровень отступа
  kamp-network:
    driver: bridge
