x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: on-failure
    logging: *default-logging
    networks:
      - kamp-network

  backend:
    build:
      context: ./backend/demo
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./uploads:/app/uploads
    logging: *default-logging
    networks:
      - kamp-network

  python-stt:
    build:
      context: ./python-stt
    container_name: python-stt
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - .env
    environment:
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
    volumes:
      - ./uploads:/app/uploads
      - ./python-stt/vosk-model:/app/vosk-model
    logging: *default-logging
    networks:
      - kamp-network

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./maria_db/data:/var/lib/mysql
    command: >
      --performance_schema=0 
      --innodb_buffer_pool_size=128M 
      --max_connections=50
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MARIADB_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - kamp-network

networks:
  kamp-network:
    driver: bridge
