x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  backend:
    build:
      context: ./backend/demo
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JAVA_OPTS=-Xms256m -Xmx768m -Xss256k -XX:MaxMetaspaceSize=128m -XX:+UseSerialGC
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "1.20"
          memory: 1024M
    logging: *default-logging
    networks:
      - kamp-network

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./maria_db/data:/var/lib/mysql
    command: >
      --performance_schema=0 
      --innodb_buffer_pool_size=128M 
      --max_connections=50
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MARIADB_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - kamp-network

networks:
  kamp-network:
    driver: bridge
