spring.application.name=demo
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET}

# Добавьте это, чтобы Hibernate не падал при первой ошибке, 
# а вывел более понятную причину
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Максимальный размер одного файла
spring.servlet.multipart.max-file-size=50MB
# Максимальный размер всего запроса
spring.servlet.multipart.max-request-size=50MB